name: "Create new release"
description: "Creates a new release for a given repo"
author: "Thomas McKeown"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  tag: 
    description: "Tag to create and use for the release"
    required: true
  previous_tag:
    description: "Tag to use as the previous. Defaults to latest tag or first commit if no tags exist"
    required: false
  commit_sha:
    description: "Commit hash to tag. Defaults to HEAD commit"
    required: false
  component:
    description: "Component name for the release"
    required: true
  jira_ticket_prefix:
    description: "Prefix for Jira tickets"
    required: true
  jira_ticket_url:
    description: "URL for the jira tickets"
    required: true
  jira_create_version_webhook:
    description: "Webhook URL for the 'Create Version' automation within Jira project"
    required: true
  jira_add_issues_webhook:
    description: "Webhook URL for the 'Add Issues' automation within Jira project"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
